t = 0:0.0001:0.1;
xa = 3 * sin(100 * %pi * t);
n = 0:30;
xn = 3 * sin(100 * %pi * n / 300);
xq = fix(xn / 0.1) * 0.1;
subplot(3, 1, 1);
plot(t, xa);
xtitle("Analog signal xa(t)", "t (s)", "Amplitude");
subplot(3, 1, 2);
plot2d3(n, xn);
xtitle("Discrete-time signal x(n)", "n", "Amplitude");
subplot(3, 1, 3);
plot2d3(n, xq);
xtitle("Quantized signal xq(n)", "n", "Amplitude");
